### ISSUE TITLE
The program was unable to successfully break the password.

### ISSUE THREAD

**Issue by Randark-JMT** [koskila/CertificatePasswordRecovery#2]
It's strange, for this pfx certificate file, I can determine the password is "123", but the tool can't blast out the password, even if it scans the password "123", the program still returns a password error.

Attached is the pfx certificate file I've been working on

[cert.zip](https://github.com/koskila/CertificatePasswordRecovery/files/12211130/cert.zip)

**Comment by koskila** [comment]
Hey @Randark-JMT and thanks for the report! You're right - it finds the password and then scans until the end anyway (at which point it'll return an error). I'll fix that.
